spring.application.name=demo

# Connection URL (Use the "Transaction" mode string from Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.hfcourvzxdvsqcsfhzhi&password=A1z2h3@4n56789
spring.datasource.username=postgres.hfcourvzxdvsqcsfhzhi
spring.datasource.password=A1z2h3@4n56789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Session Fix (Required for your pom.xml dependencies)
spring.session.jdbc.initialize-schema=always